median(tutoring$GPA)
upper <- tutoring$GPA > median(tutoring$GPA)
table(upper)
quantile(tutoring$GPA)
quant <- cut(tutoring$GPA, breaks=quantile(tutoring$GPA), include.lowest=TRUE)
table(quant)
quant <- cut(tutoring$GPA, breaks=quantile(tutoring$GPA), include.lowest=TRUE, labels=c('Gr1', 'Gr2', 'Gr3', 'Gr4'))
table(quant)
upper2 <- cut(tutoring$GPA, breaks=c(-Inf, median(tutoring$GPA), Inf), labels=c('Lower', 'Upper'))
table(upper2)
class(upper2)
